#####################################################################
#                                                                   #
# Script:  compose.override.yaml                                    #
#                                                                   #
# Purpose: Docker compose overrides for nova-api                    #
#                                                                   #
# Date:    20th November 2025                                       #
#                                                                   #
# Author:  nova admin <admin@nova.eco>                              #
#                                                                   #
#####################################################################

services:
  nova-api:
    networks:
      - '${NOVA_API__NETWORK}'
networks:
  nova-fe-network:
    driver: bridge
    internal: false
    name: '${NOVA_API__NETWORK}'
